### ISSUE TITLE
JSON Format for holdings

### ISSUE THREAD

**Issue by sirkro** [coding-sensei/dividend-portfolio-tracker#3]
Hi,

I'm writing a script for etoro and it would be nice if I could get a template for the JSON format used for holdings.

Cheers,
Sirkro

**Comment by coding-sensei** [comment]
@sirkro Thanks for reaching out, that would actually be awesome if you can write a Tampermonkey script and make a Pull request so we can add it here, that way many of the users that are not able to use regular script due to not having access to Personal Capital. I would have created a script for my UK friends, but I don't have access to that data.
Here is how the JSON for the Google Sheets is set up as:

```JSON
{
   "holdings":[
      {
         "Holding":"",
         "Shares":"8.87",
         "Price":"$1.00",
         "Value":"$8.87",
         "1 day $":"$0.00",
         "1 Day %":"0.00%"
      },
      {
         "Holding":"AAPL",
         "Shares":"131.41",
         "Price":"$116.59",
         "Value":"$15,321.55",
         "1 day $":"$73.59",
         "1 Day %":"0.48%"
      },
      {
         "Holding":"AMZN",
         "Shares":"0.8",
         "Price":"$3,195.34",
         "Value":"$2,557.77",
         "1 day $":"$8.22",
         "1 Day %":"0.32%"
      },
      {
         "Holding":"BA",
         "Shares":"2.64",
         "Price":"$216.50",
         "Value":"$570.65",
         "1 day $":"-$2.93",
         "1 Day %":"-0.51%"
      },
      {
         "Holding":"MSFT",
         "Shares":"64.39",
         "Price":"$215.23",
         "Value":"$13,859.74",
         "1 day $":"$87.58",
         "1 Day %":"0.64%"
      },
      {
         "Holding":"SBUX",
         "Shares":"19.7",
         "Price":"$98.66",
         "Value":"$1,943.66",
         "1 day $":"$9.06",
         "1 Day %":"0.47%"
      },
      {
         "Holding":"T",
         "Shares":"255.69",
         "Price":"$29.03",
         "Value":"$7,422.81",
         "1 day $":"$10.23",
         "1 Day %":"0.14%"
      },
      {
         "Holding":"V",
         "Shares":"20.46",
         "Price":"$211.00",
         "Value":"$4,318.07",
         "1 day $":"$2.25",
         "1 Day %":"0.05%"
      }
   ]
}
```
I put an example of something like Amazon that doesn't payout dividends etc and also the first holding is just set to empty by default since that is how the cash holding shows up (Honestly I think that can be skipped or ignored lol).
The extra information like
```
         "1 day $":"$2.25",
         "1 Day %":"0.05%"
```
was just included since Personal Capital provided that information, but if your brokerage doesn't have that data you can always just set them to be empty like

```
         "1 day $":"",
         "1 Day %":""
```
and that should still work :)

**Comment by sirkro** [comment]
Thanks @coding-sensei !

For "Price" is it avg. open price, current sell or buy?

for 1 day, I can do P/L data

**Comment by coding-sensei** [comment]
It might be open price, but I'm not 100% sure.
Also I might actually just remove the 
```
         "1 day $":"",
         "1 Day %":""
```

on the next release since we are getting other scripts added that are not just from personal capital so it should make it easier if we need to add other brokerages later. I might also rename the `Value` to something more meaningful since at the time I just basically used the same format that personal capital gave me.

**Comment by sirkro** [comment]
Here is a video of my adding the script and using the button https://fromsmash.com/etorotampermonkeyholdings, hope it helps

**Comment by sirkro** [comment]
I see this issue as solved :)
